apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  namespace: app
spec:
  replicas: 1
  serviceName: mysql-app-svc
  selector:
    matchLabels:
      app: mongodb-node-app
  template:
    metadata:
      labels:
        app: mongodb-node-app
    spec:
      containers:
      - name: mongo-container-name
        image: mongo
        imagePullPolicy: Always       
        ports:
        - containerPort: 27017
        env:        
        - name: MONGO_INITDB_ROOT_USERNAME
          value: santiage
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: santiagepass                                                                                                                                                             
        