kind: Service
apiVersion: v1
metadata:
  name: mysql-app-svc
  namespace: app
spec:
  selector:
    app: mongodb-node-app
  ports:
  - protocol: TCP
    name: mongodb-node-app
    port: 27017
    targetPort: 27017