apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app
spec:
  ports:
      - name: 3000-tcp
        port: 3000
        protocol: TCP
        targetPort: 3000
  selector:
    appcom.docker.project: node-app-selector
  type: ClusterIP 
